# Generated by Django 5.2.4 on 2025-07-26 17:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('team_application_id', models.IntegerField()),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('request_accepted', 'Request Accepted'), ('request_rejected', 'Request Rejected'), ('new_member_added', 'New Member Added')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='notify_noti_user_id_2f0c99_idx'), models.Index(fields=['is_read'], name='notify_noti_is_read_eee8c9_idx')],
            },
        ),
    ]
