# Generated by Django 5.2.4 on 2025-07-22 23:09

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('leader_user_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('member_user_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=[]), size=None)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=[]), size=None)),
                ('capacity', models.PositiveIntegerField()),
                ('capacity_left', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled'), ('expired', 'Expired')], default='open', max_length=10)),
                ('hackathon_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teamapplication')),
            ],
        ),
    ]
