# Generated by Django 5.2.4 on 2025-07-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
    ]
