# Generated by Django 5.2.4 on 2025-07-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
