name: Build and Publish Docker Images

on:
    push:
        branches:
            - main

jobs:
    docker:
        name: Build and Push Docker Images
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service: [user-service, team-service, notification-service] # Add other services here
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set image tag
              run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

            - name: Build and push image
              uses: docker/build-push-action@v5
              with:
                  context: ./${{ matrix.service }}
                  file: ./${{ matrix.service }}/Dockerfile
                  push: true
                  tags: tusharbaweja/hackmate-repo:${{ matrix.service }}-latest

            - name: Image digest
              run: echo "Image for ${{ matrix.service }} pushed with tag 'latest'"
